// Bundled CC-CEDICT search index (generated by `npm run data:build`).
// Covers every HSK 1–6 word with traditional, pinyin and full sense lists —
// powers lookups without any network dependency.

import * as z from 'zod'

const EntrySchema = z.object({
  t: z.string(), // traditional
  p: z.string(), // pinyin (tone-marked)
  m: z.array(z.string()), // senses
})

const IndexSchema = z.record(z.string(), EntrySchema)

export type DictEntry = z.infer<typeof EntrySchema> & { simplified: string }

let indexPromise: Promise<Record<string, DictEntry>> | null = null

function loadIndex(): Promise<Record<string, DictEntry>> {
  if (!indexPromise) {
    indexPromise = (async () => {
      try {
        const res = await fetch('/assets/deck/index/cedict-hsk.json')
        if (!res.ok) throw new Error(`index HTTP ${res.status}`)
        const raw = IndexSchema.parse(await res.json())
        const index: Record<string, DictEntry> = {}
        for (const [simplified, entry] of Object.entries(raw)) {
          index[simplified] = { simplified, ...entry }
        }
        return index
      } catch (err) {
        console.warn('[cedict] index unavailable:', err)
        return {}
      }
    })()
  }
  return indexPromise
}

/** Exact lookup: 爱 → { simplified, t, p, m }. Null when not in HSK 1–6. */
export async function lookupWord(word: string): Promise<DictEntry | null> {
  const index = await loadIndex()
  return index[word] ?? null
}

/** Prefix + substring search for typeahead (max `limit` results). */
export async function searchWords(query: string, limit = 20): Promise<DictEntry[]> {
  const index = await loadIndex()
  const q = query.trim()
  if (!q) return []
  const starts: DictEntry[] = []
  const contains: DictEntry[] = []
  for (const entry of Object.values(index)) {
    if (entry.simplified.startsWith(q)) starts.push(entry)
    else if (entry.simplified.includes(q) && contains.length < limit) contains.push(entry)
    if (starts.length >= limit) break
  }
  return [...starts, ...contains].slice(0, limit)
}
